CREATE TABLE `cotacao_historico` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cotacaoId` int NOT NULL,
	`statusAnterior` varchar(50),
	`statusNovo` varchar(50) NOT NULL,
	`observacao` text,
	`usuarioId` int,
	`sistema` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `cotacao_historico_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cotacoes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`protocolo` varchar(32) NOT NULL,
	`marca` enum('livonius','livo') NOT NULL,
	`produto` enum('rco','solar','garantia','agro','engenharia') NOT NULL,
	`status` enum('rascunho','enviado','em_analise','cotado','aceito','recusado','expirado') NOT NULL DEFAULT 'rascunho',
	`tipoPessoa` enum('pf','pj') NOT NULL,
	`cpfCnpj` varchar(18) NOT NULL,
	`nomeRazaoSocial` varchar(255) NOT NULL,
	`nomeFantasia` varchar(255),
	`telefone` varchar(20) NOT NULL,
	`whatsapp` varchar(20),
	`email` varchar(320) NOT NULL,
	`melhorHorario` varchar(50),
	`cep` varchar(10),
	`logradouro` varchar(255),
	`numero` varchar(20),
	`complemento` varchar(100),
	`bairro` varchar(100),
	`cidade` varchar(100),
	`estado` varchar(2),
	`dadosProduto` json,
	`coberturas` json,
	`documentos` json,
	`dadosExtraidos` json,
	`observacoes` text,
	`origem` varchar(50) DEFAULT 'site',
	`utmSource` varchar(100),
	`utmMedium` varchar(100),
	`utmCampaign` varchar(100),
	`crmId` varchar(100),
	`crmSyncedAt` timestamp,
	`mcpPayload` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`submittedAt` timestamp,
	CONSTRAINT `cotacoes_id` PRIMARY KEY(`id`),
	CONSTRAINT `cotacoes_protocolo_unique` UNIQUE(`protocolo`)
);
--> statement-breakpoint
CREATE TABLE `documentos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cotacaoId` int NOT NULL,
	`nomeOriginal` varchar(255) NOT NULL,
	`nomeArmazenado` varchar(255) NOT NULL,
	`mimeType` varchar(100) NOT NULL,
	`tamanho` bigint NOT NULL,
	`url` text NOT NULL,
	`fileKey` varchar(500) NOT NULL,
	`tipoDocumento` varchar(100),
	`dadosExtraidos` json,
	`extraidoEm` timestamp,
	`confiancaExtracao` int,
	`processado` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `documentos_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `form_analytics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sessionId` varchar(64) NOT NULL,
	`cotacaoId` int,
	`eventType` enum('page_view','form_start','step_view','step_complete','field_focus','field_blur','field_change','file_upload','form_submit','form_abandon','error','cta_click') NOT NULL,
	`eventData` json,
	`produto` enum('rco','solar','garantia','agro','engenharia'),
	`stepNumber` int,
	`fieldName` varchar(100),
	`timeOnStep` int,
	`totalTimeOnForm` int,
	`userAgent` text,
	`deviceType` varchar(20),
	`screenWidth` int,
	`screenHeight` int,
	`country` varchar(2),
	`region` varchar(100),
	`city` varchar(100),
	`referrer` text,
	`landingPage` text,
	`utmSource` varchar(100),
	`utmMedium` varchar(100),
	`utmCampaign` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `form_analytics_id` PRIMARY KEY(`id`)
);
