CREATE TABLE `corretores` (
	`id` int AUTO_INCREMENT NOT NULL,
	`protocolo` varchar(32) NOT NULL,
	`status` enum('pendente','em_analise','aprovado','recusado','suspenso') NOT NULL DEFAULT 'pendente',
	`cnpj` varchar(18) NOT NULL,
	`razaoSocial` varchar(255) NOT NULL,
	`nomeFantasia` varchar(255),
	`inscricaoEstadual` varchar(30),
	`cep` varchar(10),
	`logradouro` varchar(255),
	`numero` varchar(20),
	`complemento` varchar(100),
	`bairro` varchar(100),
	`cidade` varchar(100),
	`estado` varchar(2),
	`telefoneEmpresa` varchar(20),
	`emailEmpresa` varchar(320) NOT NULL,
	`website` varchar(255),
	`nomeResponsavel` varchar(255) NOT NULL,
	`cpfResponsavel` varchar(14),
	`cargoResponsavel` varchar(100),
	`telefoneResponsavel` varchar(20) NOT NULL,
	`emailResponsavel` varchar(320) NOT NULL,
	`bancoNome` varchar(100),
	`bancoCodigo` varchar(10),
	`agencia` varchar(20),
	`conta` varchar(30),
	`tipoConta` enum('corrente','poupanca'),
	`pixChave` varchar(255),
	`docContratoSocial` text,
	`docComprovanteBancarioPJ` text,
	`docComprovantesBancariosSocios` json,
	`docOutros` json,
	`susepNumero` varchar(50),
	`susepValidade` timestamp,
	`observacoes` text,
	`motivoRecusa` text,
	`crmId` varchar(100),
	`crmSyncedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`aprovadoEm` timestamp,
	`aprovadoPor` int,
	CONSTRAINT `corretores_id` PRIMARY KEY(`id`),
	CONSTRAINT `corretores_protocolo_unique` UNIQUE(`protocolo`),
	CONSTRAINT `corretores_cnpj_unique` UNIQUE(`cnpj`)
);
--> statement-breakpoint
CREATE TABLE `sinistro_historico` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sinistroId` int NOT NULL,
	`statusAnterior` varchar(50),
	`statusNovo` varchar(50) NOT NULL,
	`observacao` text,
	`usuarioId` int,
	`sistema` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `sinistro_historico_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sinistros` (
	`id` int AUTO_INCREMENT NOT NULL,
	`protocolo` varchar(32) NOT NULL,
	`marca` enum('livonius','livo') NOT NULL,
	`produto` enum('rco','solar','garantia','agro','engenharia') NOT NULL,
	`tipoSinistro` varchar(100) NOT NULL,
	`status` enum('aberto','documentacao_pendente','em_analise','vistoria_agendada','aguardando_laudo','em_regulacao','aprovado','parcialmente_aprovado','negado','pago','encerrado') NOT NULL DEFAULT 'aberto',
	`tipoPessoa` enum('pf','pj') NOT NULL,
	`cpfCnpj` varchar(18) NOT NULL,
	`nomeRazaoSocial` varchar(255) NOT NULL,
	`telefone` varchar(20) NOT NULL,
	`whatsapp` varchar(20),
	`email` varchar(320) NOT NULL,
	`numeroApolice` varchar(50),
	`vigenciaInicio` timestamp,
	`vigenciaFim` timestamp,
	`dataOcorrencia` timestamp NOT NULL,
	`horaOcorrencia` varchar(10),
	`localOcorrencia` text,
	`descricaoOcorrencia` text NOT NULL,
	`dadosSinistro` json,
	`placaVeiculo` varchar(10),
	`marcaModeloVeiculo` varchar(100),
	`anoVeiculo` varchar(10),
	`chassiVeiculo` varchar(30),
	`nomeCondutor` varchar(255),
	`cnhCondutor` varchar(20),
	`vitimas` json,
	`terceiros` json,
	`valorEstimado` bigint,
	`valorAprovado` bigint,
	`valorPago` bigint,
	`docBoletimOcorrencia` text,
	`docCRLV` text,
	`docCNH` text,
	`docFotos` json,
	`docLaudoTecnico` text,
	`docRelatorioMedico` text,
	`docOrcamentos` json,
	`docNotasFiscais` json,
	`docOutros` json,
	`observacoes` text,
	`motivoNegativa` text,
	`crmId` varchar(100),
	`crmSyncedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`encerradoEm` timestamp,
	CONSTRAINT `sinistros_id` PRIMARY KEY(`id`),
	CONSTRAINT `sinistros_protocolo_unique` UNIQUE(`protocolo`)
);
